version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env 
    volumes:
      - .:/app  
      - /app/node_modules # Exclude node_modules from the volume mapping
    ports:
      - "3000:3000"
    user: node
